Feature/52/SystemMessageCell의 특정문구의 HyperLink 구현
Team-TravelGenie/TripChat pull request #106
Opened 2023-09-19 09:22 UTC by iOS-Woong

**하이퍼링크 구현리스트**
- OpenAI의 데이터 사용 정책
- Google API의 서비스이용약관
- Google API 사용자 데이터 정책
- NAVER Developers 운영 정책

++ SystemButtonCell의 상단문구를 탭하여 접근가능하도록 구현해두었습니다!

2023-09-19 15:51 UTC, dev-summer requested changes
확인 완료입니다!
수정 요청드린 부분만 수정 부탁드립니다~

2023-09-19 15:51 UTC, dev-summer commented on TravelGenie/TravelGenie/Extensions/NSMutableAttributedString+text.swift
> +        return baseAttributedString
타입 이름이 `Hyperlink`이니 `linkText`보다는 `hyperlinkText`로 결을 같이 맞춰주는게 좋을 것 같아요.

2023-09-19 15:51 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/View/Cell/DefaultSystemSectionCell/SystemMessageCell.swift
> +        welcomeMessageTextView.backgroundColor = .blueGrayBackground
배경색은 `.clear`로 주는 게 더 좋아보여요.

2023-09-19 15:51 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/HyperLink.swift
> +    enum HyperLinkType {
Hyperlink라고 수정해주시면 더 좋을 것 같아요~
https://en.wikipedia.org/wiki/Hyperlink

2023-09-19 15:51 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/SystemMessageViewModel.swift
> +        입력 데이터는 OpenAI의 데이터 사용 정책, Google API의 서비스이용약관, Google API 사용자 데이터 정책, NAVER Developers 운영 정책에따라 관리됩니다.이 서비스는 초기버전으로 AI 답변의 신뢰성과 사용 시 생기는 문제에 책임을 지지 않으며 사정에 따라 사전 안내없이 중단 할 수 있습니다.개인 정보를 입력하지
띄어쓰기 수정 요청

입력 데이터는 OpenAI의 데이터 사용 정책, Google API의 서비스 이용약관, Google API 사용자 데이터 정책, NAVER Developers 운영 정책에 따라 관리됩니다. 이 서비스는 초기버전으로 AI 답변의 신뢰성과 사용 시 생기는 문제에 책임을 지지 않으며 사정에 따라 사전 안내없이 중단 할 수 있습니다. 개인 정보를 입력하지 않도록 유의해 주세요.

2023-09-19 15:51 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/HyperLink.swift
> +            return "Google API의 서비스이용약관"
띄어쓰기 수정요청

서비스 이용약관

2023-09-20 10:14 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Extensions/NSMutableAttributedString+text.swift
> +        return baseAttributedString
수정완료되었습니다

2023-09-20 10:17 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/View/Cell/DefaultSystemSectionCell/SystemMessageCell.swift
> +        welcomeMessageTextView.backgroundColor = .blueGrayBackground
그러네요
수정완료하였습니다!

2023-09-20 10:21 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/HyperLink.swift
> +    enum HyperLinkType {
굿 좋아여 수정완료하였습니다!

2023-09-20 10:24 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/SystemMessageViewModel.swift
> +        입력 데이터는 OpenAI의 데이터 사용 정책, Google API의 서비스이용약관, Google API 사용자 데이터 정책, NAVER Developers 운영 정책에따라 관리됩니다.이 서비스는 초기버전으로 AI 답변의 신뢰성과 사용 시 생기는 문제에 책임을 지지 않으며 사정에 따라 사전 안내없이 중단 할 수 있습니다.개인 정보를 입력하지
꼼꼼하게 봐주셔서 감사합니당
수정하였습니다!

2023-09-20 10:24 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/HyperLink.swift
> +            return "Google API의 서비스이용약관"
수정완료되었습니다

2023-09-20 17:20 UTC, dev-summer approved these changes

2023-09-22 05:59 UTC, merged