Feat/61/Tripadvisor API
Team-TravelGenie/TripChat pull request #123
Opened 2023-09-25 07:37 UTC by iOS-Woong

**구현범위**
- API, Repository, UseCase

++ PR/59 RecommendationItem이 머지되면 추가작업 이어나가보겠습니다!

2023-09-25 11:19 UTC, dev-summer commented on TravelGenie/TravelGenie/Domain/RepositoryInterface/LocationPhotosRepository.swift
> +}
추상화를 하는 이유에 관해 고민이 필요할 것 같습니다!

해당 `Repository`에서는 `1. 장소 검색`, `2. 사진 검색`의 두 가지 역할이 구현되어 있는데요,
`사진 검색`이라는 사용자 흐름은 이미 `ImageSearchRepository`와 `ImageSearchUseCase`에서 담당하고 있다고 생각해요.

그리고 저는 `Repository`를 추상화 하는 이유가 나중에 `searchLocation`이나 `searchPhotos`에서 사용하는 API가 변경되었을 때 해당 `Repository` 프로토콜을 채택하는 구체 타입만 만들어 주면 되도록 하는 거라고 생각합니다.
하지만 지금의 구현으로는 `LocationPhotosRepository`를 채택하는 새로운 구체 타입을 만들 경우 반드시 `searchLocation`과 `searchPhotos`를 모두 구현해야 하죠. 만약 장소를 가져오는 것만 다른 API로 변경하거나 사진을 가져오는 것만 다른 API로 변경하려면 사용하지 않는 메서드도 요구사항에 들어가게 되거나, 새로운 `Repository` 프로토콜을 만들어야 할 것 같습니다.

위의 두 가지 이유로, **사용하는 API 중심이 아니라 `UseCase`와 `Repository`의 역할 중심**으로 재설계하면 어떨까..? 라는 생각이 들어요.

여기에 대한 웅의 의견이 궁금합니다!

2023-09-25 11:21 UTC, dev-summer requested changes

2023-09-25 11:21 UTC, dev-summer commented on TravelGenie/TravelGenie/Domain/RepositoryInterface/LocationPhotosRepository.swift
> +}
추상화를 하는 이유에 관해 고민이 필요할 것 같습니다!

해당 Repository에서는 1. 장소 검색, 2. 사진 검색의 두 가지 역할이 구현되어 있는데요,
사진 검색이라는 사용자 흐름은 이미 ImageSearchRepository와 ImageSearchUseCase에서 담당하고 있다고 생각해요.

그리고 저는 Repository를 추상화 하는 이유가 나중에 searchLocation이나 searchPhotos에서 사용하는 API가 변경되었을 때 해당 Repository 프로토콜을 채택하는 구체 타입만 만들어 주면 되도록 하는 거라고 생각합니다.
하지만 지금의 구현으로는 LocationPhotosRepository를 채택하는 새로운 구체 타입을 만들 경우 반드시 searchLocation과 searchPhotos를 모두 구현해야 하죠. 만약 장소를 가져오는 것만 다른 API로 변경하거나 사진을 가져오는 것만 다른 API로 변경하려면 사용하지 않는 메서드도 요구사항에 들어가게 되거나, 새로운 Repository 프로토콜을 만들어야 할 것 같습니다.

위의 두 가지 이유로, 사용하는 API 중심이 아니라 UseCase와 Repository의 역할 중심으로 재설계하면 어떨까..? 라는 생각이 들어요.

여기에 대한 웅의 의견이 궁금합니다!

2023-09-26 07:34 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Domain/RepositoryInterface/LocationPhotosRepository.swift
> +}
우선, 저의 의도는 아래입니다.

1. 현재, 제가 의도하는 동작은 Tripadvisor에서 사진API를 통해 사진을 가져오는 행위
2. 해당 API에선 `사진검색`을 하기위해선 `장소검색`을 필수적으로 선행하도록 설계됨
3. `장소검색`의 역할은 단지 `사진검색`에 필요한 ID값을 반환시키려는 것
4. 따라서, `장소검색`은 `사진검색`만을 위해서 수행하는 행위이기에 이것은 `사진검색`이 포함하도록 설계
---

> 하지만 지금의 구현으로는 LocationPhotosRepository를 채택하는 새로운 구체 타입을 만들 경우 반드시 searchLocation과 searchPhotos를 모두 구현해야 하죠. 
> 만약 장소를 가져오는 것만 다른 API로 변경하거나 사진을 가져오는 것만 다른 API로 변경하려면 사용하지 않는 메서드도 요구사항에 들어가게 되거나, 새로운 Repository 프로토콜을 만들어야 할 것 같습니다.

- '사진을 가져오는 것만 다른 API로 변경하려면'을 수행하려면 현재의 searchPhoto, searchLocation을 모두 요구하는 프로토콜로 인해 새로운 Repository 프로토콜을 만들어야 하는 문제가 발생

> 마지막으로 현재의 구현은 장소 검색과 사진 검색이라는 두 가지 별도의 시나리오 간 결합성이 높지 않은가? 라는 생각이 들어요.

- 만약, 앱을 추후에 발전시켜 `Location Detail`이라는 API를 불러야 할 상황이 생긴다고 가정했을 때 
(이 API도 searchLocation의 선행하여 locationID를 요구함)
- searchLocation은 독립적이여야 적합할 것 같습니다

---

감사합니다 모캣 굉장히 정확하게 봐 주신 것 같습니당
섬캣의 의도를 정확하게 이해하려고 좀 오랫동안 붙잡고 있었네요
저는 아래와 같이 재설계 해보려고 합니다.

```swift
// 기존
searchLocation - UseCase 

// 수정
searchLocationRepo - UseCase 
searchPhotosRepo - UseCase
```


> 위의 세 가지 이유로, 사용하는 API 중심이 아니라 UseCase와 Repository의 역할 중심으로 재설계하면 어떨까..?

근데 위 이야기는 조금 이해가 되지 않았습니다.
혹시 이부분에 대해서 의도를 조금만 더 설명해주시면 이해하는데 도움이 될 것 같아요!

2023-09-26 13:33 UTC, iOS-Woong commented
수정완료되었습니다!

2023-09-26 13:41 UTC, dev-summer requested changes

2023-09-26 13:41 UTC, dev-summer commented on TravelGenie/TravelGenie/Data/Network/ResponseModel/LocationPhotosDTO.swift
> +struct LocationPhotosDTO: Codable {
해당 타입은 Decode하는 경우의 수만 존재하는 것 같은데,
해당 타입과 nested type들이 `Decodable`을 채택하도록 변경해주면 좋을 것 같아요

2023-09-26 13:41 UTC, dev-summer commented on TravelGenie/TravelGenie/Data/Network/ResponseModel/LocationSearchDTO.swift
> +struct LocationSearchDTO: Codable {
여기도 마찬가지로 전부 `Decodable`로 변경해주면 좋을 것 같아요

2023-09-26 13:41 UTC, dev-summer commented on TravelGenie/TravelGenie/Data/Repository/DefaultLocationPhotosRepository.swift
> +                let locationID = response.data[0].locationID
이거 제가 작성한 코드에서도 수정이 필요한 부분인데, 리스폰스가 비어있을 경우가 고려되지 않은 것 같습니다 (보낸 쿼리에 해당하는 장소가 없을 경우).
`locationID = responsedata.first`로 하고 비어있을 경우 `completion(error)`로 보내주도록 리팩토링이 필요할 것 같아요
(에러 유형을 별도로 지정해주면 더 좋고요).

2023-09-26 13:41 UTC, dev-summer commented on TravelGenie/TravelGenie/Data/Repository/DefaultLocationSearchRepository.swift
> +                let imageUrl = response.data[0].images.large.url
여기도 마찬가지로 리스폰스가 비어있을 경우에 대해 고려가 필요해 보입니다!

2023-09-26 13:43 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Data/Network/ResponseModel/LocationPhotosDTO.swift
> +struct LocationPhotosDTO: Codable {
수정완료되었습니다!

2023-09-26 13:43 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Data/Network/ResponseModel/LocationSearchDTO.swift
> +struct LocationSearchDTO: Codable {
수정완료되었습니다!

2023-09-26 13:44 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Data/Repository/DefaultLocationPhotosRepository.swift
> +                let locationID = response.data[0].locationID
아하 이부분 놓치고있었네요 감사합니당

2023-09-26 14:14 UTC, dev-summer requested changes
새로이 `ResponseError`를 정의해 주었으니, 각 Repository의 메서드에서 매개변수로 받는 클로저의 Result타입의 에러의 타입이 그냥 `Error`가  아니라 `ResponseError` 타입으로 변경해 주는 것이 좋지 않을까요?

2023-09-26 14:16 UTC, dev-summer commented on TravelGenie/TravelGenie/Data/Repository/DefaultImageSearchRepository.swift
> +                    completion(.failure(ResponseError.emptyResponse))
`.failure(.emptyResponse)`와 같이 표기할 수 있을 것 같아요

2023-09-26 14:20 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Data/Repository/DefaultImageSearchRepository.swift
> +                    completion(.failure(ResponseError.emptyResponse))
수정되었습니다!

2023-09-26 14:23 UTC, dev-summer approved these changes

2023-09-26 14:23 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Data/Repository/DefaultLocationPhotosRepository.swift
> +                let locationID = response.data[0].locationID
ImageSearchRespository의 변경사항까지 반영되었습니당

2023-09-26 14:31 UTC, merged