Feat/67/CopyToastView
Team-TravelGenie/TripChat pull request #135
Opened 2023-10-04 07:41 UTC by iOS-Woong

**CopyToastView의 구현**
- CopyToastVC를 생성하여 present하는 방식 (X) / CopytoastView를 생성하고 homeViewController에서 뷰를 추가 및 제거하는 방식 (O)
- 의도: ToastView가 보여지는 상태에서도 사용자의 인터랙션을 막지않으려는 의도
- 이유: ToastView를 present하게되면 인터랙션을 막게되더라구요

2023-10-04 08:03 UTC, dev-summer requested changes
하나만 확인 부탁드립니다~~

2023-10-04 08:03 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Home/View/CopyToastView.swift
> +        static let toastViewHeightProportionToParent: CGFloat = 0.0714
디자인가이드에는 너비 343, 높이 58인데 비율로 별도로 지정해주신 이유가 있나요?

2023-10-04 08:03 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Home/View/CopyToastView.swift
> +        static let toastViewHeightProportionToParent: CGFloat = 0.0714
기기 사이즈에 따라 토스트UI 크기가 바뀌어야 한다고 생각하시면 디자이너분이랑 논의가 필요할 것 같아요!

2023-10-04 09:27 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Home/View/CopyToastView.swift
> +        static let toastViewHeightProportionToParent: CGFloat = 0.0714
디자인가이드에서 제공하는 343 / 58 사이즈를 equalToConstant로 설정하면 화면에서 보이는 토스트뷰가 큰 기기에선 좀 작게 표현되는 경향이 있었습니다.
따라서, 디자인가이드에서 제공하는 기기사이즈 너비/높이에 대비한 컴포넌트의 값을 계산하여 
multiplier로 지정해주면 가이드에서 원하는 UI 형태로 모든 기기에서 거의 동일하게 표현될 수 있겠다 이렇게 생각하였네요

```
기기의 사이즈 (w: 375 / h: 812) 중, 디자인 가이드 컴포넌트의 사이즈 (w: 343 h: 58)의 비율

widthRatio = 0.9146
heightRatio = 0.0714
```

근데 이 케이스의 경우, 
디자이너가 의도하는 사이즈가 모든 기기에서 (w: 343 h: 58)라고 명시해뒀으므로 이건 해당 사이즈를 지키는게 맞는 것 같네요

수정완료되었습니당 ~

2023-10-04 13:23 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Home/View/CopyToastView.swift
> +        static let toastViewHeightProportionToParent: CGFloat = 0.0714
넵 혹시나 작은 기기에서 표시되지 않을까 우려가 있다면 디자이너와 상의해서 왼쪽/오른쪽 마진 값으로 제약을 주는 것도 좋을 것 같습니다~

2023-10-05 02:39 UTC, dev-summer approved these changes

2023-10-05 07:11 UTC, merged