Feature/46/태그셀 리팩토링
Team-TravelGenie/TripChat pull request #94
Opened 2023-09-13 07:17 UTC by iOS-Woong

**태그 제출 후에도 SubmitKeywordButton이 동작하는 버그 수정**
- tag를 제출했음에도 tag가 선택되거나 submitKewordButton이 계속 동작하는 버그를 제거

**태그 제출 후에 MessageStorage가 변경사항을 반영하지 못하던 버그 수정**
- 기존 코드에선 tag를 제출한 후에도 MessageStorage가 이를 반영하지 못하였었습니다.
- 따라서, 해당 태그셀이 리로드되면 선택사항을 반영하지 못하고 모든 선택이 제거되어버리는 현상이 있었고 이를 수정

**TagItem의 category로 keword를 추가** 
- defaultKeword로 5가지를 포함하여 [관광], [음식], [역사탐방], [휴양], [액티비티]를 포함하도록 수정
- TagCell을 Self-Size하는 로직을 일부조정

**외부에서 TagCell의 버튼을 비활성하는 로직을 수정** 
- buttonStateDelegate의 함수가 인자로 interaction과 submitButton의 상태를 각각받도록 수정

2023-09-13 09:12 UTC, dev-summer requested changes
> 오차범위 16정의, 섹션이 한개 늘어났을 때 16가랑의 오차가 발생하는데 원인은 정확히 파악되지않는 상태

에 대한 부분은 `LeftAlignedCollectionViewFlowLayout`의 계산 로직 문제인 것 같아서 별도 브랜치에서 나중에 해결해 보는걸로 하시져

고생하셨습니다!

2023-09-13 14:17 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/View/Cell/CustomTagCell/CustomTagContentCell.swift
> +        return tagCollectionViewContentHeight + messageLabelHeight + submitKeywordButtonHeight - accuracyLimit
이번 PR에서 바로 해결할 문제가 아니라면 커밋에만 해당 사항을 적는게 아니라, 주석으로도 적어주면 나중에 확인하기가 더 수월할 것 같아요.

2023-09-15 04:26 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/ChatInterfaceViewModel.swift
> +            didChangeUploadButtonState?()
그게 더 적절해보이네요
수정완료하였습니다!

2023-09-15 07:22 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/ChatInterfaceViewModel.swift
> +    private (set) var tagCellInteractionStates = (submitButtonState: false, interaction: true) {
의도와 조금 맞지않는 구현이였던 것 같네요. 현재 아래와 같이 수정하여씀미당
혹시라도 이건 좀 별로라는 생각있다면 말씀해주세요!

---

**버튼의 상태변수를 하나만 만들어준 이유**
- 아래는 didChangeTagCellInteractionState에 대한 바인딩입니다.
(TagCell의 상태가 변환되면 MessageStorage 내 TagMessage를 찾아서 해당 인덱스에 대한 섹션을 리로드하도록 되어있습니다.)
- 만약, 두개의 상태변수를 만들어준다면 `button의상태변수` `collectionView의상태변수`가 변경될 경우 2회의 섹션의 리로드가 발생하므로 제가 의도하는 방법은 아니였습니당.
- 그걸 튜플로 한번에 할당하여 2번 리로드되는 것을 해결하려는 의도였습니다.

```swift
// func bind()
chatInterfaceViewModel.didChangeTagCellInteractionState = { [weak self] in
    guard let tagMessageIndex = self?.chatInterfaceViewModel.messageStorage.findTagMessageIndex() else {
        print("MessageStorage에서 TagMessage를 찾지못헀음")
        return
    }
    let indexSet = IndexSet(integer: tagMessageIndex)
    
    DispatchQueue.main.async {
        UIView.performWithoutAnimation {
            self?.messagesCollectionView.reloadSections(indexSet)
        }
    }
}
```

- 하지만, 이렇게 작업을하고보니 문제가 있었는데 가독성에도 문제가 있고(의도를 알아채기힘듦)
- 마음먹으면 tagCellInteractionStates.submitButtonState = someState1, tagCellInteractionStates.interaction = someState2로 접근가능하게 되더라구요
- 이는 만약 저희가 추가적인 유지보수가 있다면 구현사항을 잊고 각각 값을 할당할 경우가 있을 것 같더라구요.(2회리로드)

```swift
// 기존코드
private (set) var tagCellInteractionStates = (submitButtonState: false, interaction: true) { }
```

- 따라서, 아래의 TagMessageInteractionState라는 타입을 만들고, 2개의 상태가 변환되더라도 1번의 리로드만 발생하도록 구현하였습니다.

```swift
// buttonStateDelegate.setTagCellButtonState
func setTagCellButtonState(submitButtonState: Bool, interactionState: Bool) {
    let state = TagMessageInteractionState(submitButtonState: submitButtonState, interactionState: interactionState)
    
    tagMessageInteractionState = state
}

// TagMessageInteractionState ..
struct TagMessageInteractionState {
    private (set) var submitButtonState: Bool
    private (set) var interactionState: Bool
    
    init(submitButtonState: Bool = false, interactionState: Bool = true) {
        self.submitButtonState = submitButtonState
        self.interactionState = interactionState
    }
}
```

> 태그셀이 상호작용 가능한 상태인지를 나타내는 변수인데, submitButton의 상태까지 담고 있는 것은 이상한 것 같아요.

- 이부분도 맞는 말씀 인 것 같습니다.  
- 따라서 기존의 TagCellInteractionStates의 네이밍을 TagMessageInteractionState으로 수정하였습니다.
- 하위로 태그메시지가 포함하고있는 상호작용요소인 submitButtonState과 CollectionViewCell InteractionState를 담도록 하였습니다.

```
// 수정된 ChatInterfaceVM 
// 역할 (ChatVM / HistoryVM 에서 TagMessge의 상호작용을 제어하는 목적의 상태변수 및 클로저)

var didChangeTagMessageInteractionState: (() -> Void)?

private (set) var tagMessageInteractionState = TagMessageInteractionState() {
    didSet {
        didChangeTagMessageInteractionState?()
    }
}
```

2023-09-15 07:23 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/View/Cell/CustomTagCell/CustomTagContentCell.swift
> +        tagCollectionView.isUserInteractionEnabled = state.1
TagMessageInteractionState 객체를 전달해줌으로써 
튜플로 표현하는 방식은 수정되었습니다

2023-09-15 07:27 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/View/Cell/CustomTagCell/CustomTagContentCell.swift
> +        return tagCollectionViewContentHeight + messageLabelHeight + submitKeywordButtonHeight - accuracyLimit
주석을 남겨뒀습니다. 
```
// 2개의 섹션으로 사이즈 측정시엔 문제가없었는데, 3개의 섹션을 활용하였을 때, tagCollectionViewContentHeight에서 16.0 가량의 오차가 발생하였습니다.
// 정확한 원인은 아직 파악하지 못하였습니다. 해결이 필요 할 것 같습니다.
// 현재는 임시방편으로 -16.0으로 계산되도록 구현해두었습니다.
let accuracyLimit = 16.0
```
정확한 원인을 잘 모르겠더라구요... ㅠㅠ

2023-09-15 07:40 UTC, iOS-Woong commented
**에러로그에 대한 해결**
```
2023-09-14 17:33:32.692888+0900 TravelGenie[661:17978] Logging only once for UICollectionViewFlowLayout cache mismatched frame
2023-09-14 17:33:32.692980+0900 TravelGenie[661:17978] UICollectionViewFlowLayout has cached frame mismatch for index path <NSIndexPath: 0xb6b542dce7928710> {length = 2, path = 0 - 1} - cached value: {{82, 27}, {74, 47}}; expected value: {{130, 27}, {74, 47}}
2023-09-14 17:33:32.693011+0900 TravelGenie[661:17978] This is likely occurring because the flow layout subclass TravelGenie.LeftAlignedCollectionViewFlowLayout is modifying attributes returned by UICollectionViewFlowLayout without copying them
```

아래 코드는 원문입니다.

```swift
// LeftAlignedCollectionViewFlowLayout.swift...

override func layoutAttributesForElements(in rect: CGRect) -> [UICollectionViewLayoutAttributes]? {
    guard let originAttributes = super.layoutAttributesForElements(in: rect) else { return nil }
    
    var leftMargin = sectionInset.left
    var maxY: CGFloat = originAttributes.first?.frame.origin.y ?? 0
    
    let adjustAttributes = originAttributes.map { layoutAttribute -> UICollectionViewLayoutAttributes in
        let isCell = layoutAttribute.representedElementCategory == .cell
        let isHeader = layoutAttribute.representedElementCategory == .supplementaryView
        
        if isCell {
            // 현재 셀의 new row를 그린 상태라면, 좌측 정렬하라.
            if layoutAttribute.frame.origin.y >= maxY {
                leftMargin = sectionInset.left
            }
            
            layoutAttribute.frame.origin.x = leftMargin
            
            // 셀 너비와 항목 간 간격만큼 왼쪽 여백 증가
            let totalCellWidth = layoutAttribute.frame.width + customMinimumInteritemSpacingForSectionAt
            leftMargin += totalCellWidth
            
            // maxY 값 업데이트, 현재 행의 최대 y 위치를 추적
            maxY = max(layoutAttribute.frame.maxY, maxY)
            totalHeight = maxY
        }
        
        // totalHeight에 값을 더해주는 이유는 CustomTagContentCell의 messageContainer를 사이즈를 다시 그려주기 위해서입니다.
        if isHeader {
            totalHeight += layoutAttribute.frame.height
        }
        
        return layoutAttribute
    }
    
    return adjustAttributes
}
```

**문제의 해결**

originAttributes의 타입은 [UICollectionViewFlowLayoutAttributes] 타입으로 
Swift의 Collection(값)으로 반환하고 있습니다.

따라서, 이전 코드에서 참조타입의 컬렉션(배열)을 map으로 각각 수정하려고 시도하니
0인덱스의 UICollectionViewLayoutAttributes 객체를 수정하면, 1에도 영향을 미치고 2에도 영향을 미치게되는 문제로 인해 발생하는 문제였습니다. 

따라서, copy()를 통해 값을 참조타입을 복사하여 복사된 layoutAttributes를 return하는 방식으로 문제가 해결되었습니다.
```swift
let adjustAttributes = originAttributes.compactMap { originalAttribute -> UICollectionViewLayoutAttributes? in
guard let layoutAttribute = originalAttribute.copy() as? UICollectionViewLayoutAttributes else { return nil }
```


[참조링크](https://stackoverflow.com/questions/31771089/when-using-subclassed-collectionviewflowlayout-im-getting-weird-error)

2023-09-15 07:53 UTC, iOS-Woong commented on TravelGenie/TravelGenie.xcodeproj/xcuserdata/hyeonung-seo.xcuserdatad/xcschemes/xcschememanagement.plist
> -			<integer>1</integer>
이거 reset file하여 커밋이전의 상태로 돌려뒀습니다!

2023-09-15 07:59 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/ChatInterfaceViewModel.swift
> +    private (set) var tagCellInteractionStates = (submitButtonState: false, interaction: true) {
잘 수정된 것 같습니다!
아래에서 추가로 코멘트 드린 부분만 확인하시고 머지 진행하시면 될것 같습니다~

2023-09-15 08:01 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/View/Cell/CustomTagCell/TagMessageInteractionState.swift
> +    private (set) var interactionState: Bool
아 좋슴당
수정완료하였습니다!

2023-09-15 08:18 UTC, merged