Feature/47/태그컬렉션뷰 태그의 사이즈 계산법 리팩토링
Team-TravelGenie/TripChat pull request #96
Opened 2023-09-18 06:55 UTC by iOS-Woong

**개선점**
- 기존의 tagCell의 Width 계산방법은 defaultWidth 48.0에서 `1글자 당 13.0을 더해주는 방식`으로 구현되어있었음.
ex) "#국내"의 경우 -- defaultWidth + 3(글자수) * 13.0
- 하지만, 이 방법은 한글에선 정상적으로 동작하나 영문이 들어가는 경우 너무 길어지게 되는 문제가 있었음
- 따라서, `적용된 폰트에서의 문자열의 실제 너비를 계산하여 반환하는 방식`으로 구현을 변경하였음.

![image](https://github.com/Team-TravelGenie/TripChat/assets/96489602/1d167e29-07d5-402c-adc3-d946dd1afd28)

| - | 1글자 | 2글자 | 3글자 | 4글자 | 5글자 |
|---------|---------|---------|---------|---------|---------|
| **기존 한글**| 61.0 | 74.0  | 87.0 | 100.0 | 113.0 |---------|
| **개선 한글**| 60.975 | 73.95  | 86.975 | 99.9 | 112.875 |
| **개선 영문**| 56.60.. | 66.14.. | 74.72.. | 84.25.. | 93.03.. | 
| **개선 특문**| 57.83.. | 67.67.. | 77.50.. | 87.34.. | 97.18.. |

- 기존의 구현에선 디자인가이드에서 제공하는 문자수 별  셀 사이즈를 준수하고있지만,
현재의 구현에선 소수점 단위의 약간의 오차가 존재합니다.

2023-09-18 07:05 UTC, dev-summer requested changes

2023-09-18 07:05 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/CustomTagContentCellViewModel.swift
> +import UIKit
가급적이면 ViewModel에서 `import UIKit`하지 않는 편이 좋다고 생각하는데, 꼭 필요한 이유가 있을까요?
제거하거나 다른 타입으로 넘겨줄 수 있는 방법을 찾으면 좋을 것 같아요

2023-09-18 07:05 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/CustomTagContentCellViewModel.swift
> +import UIKit
이전 커밋에서 `UIFont`를 사용하는 코드를 추가해서 이 커밋에서 `import UIKit`을 추가하신 것 같은데,
사이즈를 구하는 코드를 다른곳으로 빼거나, extension에 구현하거나 방법은 여러가지가 있을 거 같아요.

2023-09-18 07:05 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/CustomTagContentCellViewModel.swift
> +        let padding: CGFloat = 48.0
패딩 값이 어떻게 나온 값인지 알 수 있을까요?
디자인 가이드 상으로는 좌/우 각각 20pt 씩인걸로 되어있어서요!

2023-09-18 07:50 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/CustomTagContentCellViewModel.swift
> +        let padding: CGFloat = 48.0
태그라벨의 설정폰트 bodyBold (systemFont 15, weight: .bold) 로
한글라벨의 사이즈를 산출했을때, 
대략적으로 값은 아래와 같습니당

---

**개선후, 산출된 라벨사이즈**
2글자: 25.95
3글자: 38.925
4글자: 51.9
5글자: 64.875

**가이드 라벨사이즈**
2글자: 34
3글자: 47
4글자: 60
5글자: 73

---

여기에 대한 오차가 약 8.0 ~ 8.3 사이에서 좀 있는 것 같아요
따라서, 기존의 padding 40에서 8을 추가해주었습니다

지금의 0.x ~ 0.x 에 대한 범위는 유동적이나 너무 작아서 고려하진않았습니다

2023-09-18 08:19 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/CustomTagContentCellViewModel.swift
> +        let padding: CGFloat = 48.0
```swift
func calculatedCellSizeForTag() -> CGSize {
    let font = UIFont.systemFont(ofSize: Font.bodyBold.fontSize, weight: Font.bodyBold.weight)
    let tagValueSize = (self as NSString).size(withAttributes: [NSAttributedString.Key.font: font])
    
    let padding: CGFloat = 40.0
    let sizeAdjustment: CGFloat = 8.0
    let defaultHeight: CGFloat = 47.0

    let widthResult = tagValueSize.width + padding + sizeAdjustment
    
    return CGSize(width: widthResult, height: defaultHeight)
}
```

일단, sizeAdjustment를 상수로 빼두었습니다!

2023-09-18 08:19 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/CustomTagContentCellViewModel.swift
> +import UIKit
extension으로 빼는방법이 좋을 것 같네요
해당 부분을 수정구현하였습니다!

2023-09-18 09:27 UTC, dev-summer requested changes

2023-09-18 09:27 UTC, dev-summer commented on TravelGenie/TravelGenie/Extensions/String+calculatedCellSizeForTag.swift
> +        return CGSize(width: widthResult, height: defaultHeight)
일정한 숫자(`8`)만큼 차이나는 이유는 현재 셀 크기를 계산하는 로직에 `#`을 제외한 키워드 부분만을 계산하고 있어 그런 것 같네요 (태그셀에 들어갈 내용이 `#국내`라면 `국내`만 가지고 계산).
가이드 라벨 사이즈는 `좌측패딩 + 라벨가로크기 + 우측패딩`에 `hug`로 자동 계산되어 있는 거라고 보시면 될 거 같고요 (세로도 마찬가지로 `탑패딩 + 라벨세로크기 + 아래패딩`).

![image](https://github.com/Team-TravelGenie/TripChat/assets/98260324/f387803d-cc8c-4c0a-ba3e-19616a89a126)

결론은
1. `padding`을 가이드에서 좌/우 패딩 20씩으로 주고 있으니 그냥 `40`으로 하는 것보다 그 의미를 담아주면 좋지 않을까요?
2. `height`도 상수를 지정하는 거보다 같은 방식으로 계산해주면 더 좋을 것 같습니다.
3. `#`만큼의 크기 차이가 나니 이건 방법이 2가지가 있겠네요
    - `tagValueSize`를 계산하기 전에 `#`을 String에 append한 후 계산
    - `sizeAdjustment` 변수의 이름을 변경
    - 저는 개인적으로 첫 번째 방법이 더 좋다고 생각합니다.

2023-09-18 09:27 UTC, dev-summer commented on TravelGenie/TravelGenie/Presentation/Chat/ViewModel/CustomTagContentCellViewModel.swift
> +        let padding: CGFloat = 48.0
아하 사용하신 이유를 자세히 알려주셔서 원인을 파악하는 데 도움이 되었습니다!
추가적인 커멘트는 수정된 코드에 달았습니다.

2023-09-18 10:32 UTC, iOS-Woong commented on TravelGenie/TravelGenie/Extensions/String+calculatedCellSizeForTag.swift
> +        return CGSize(width: widthResult, height: defaultHeight)
결과적으로 아래와 같이 구현하였습니다. 

```swift
extension String {
    func calculatedCellSizeForTag() -> CGSize {
        let prefixedTagValue = "#\(self)"
        
        let font = UIFont.systemFont(ofSize: Font.bodyBold.fontSize, weight: Font.bodyBold.weight)
        let tagValueSize = (prefixedTagValue as NSString).size(withAttributes: [NSAttributedString.Key.font: font])
        
        let leadingTrailingPadding: CGFloat = 20.0 * 2
        let defaultHeight = 47.0
        
        let widthResult = tagValueSize.width + leadingTrailingPadding
        
        return CGSize(width: widthResult, height: defaultHeight)
    }
}
```

> height도 상수를 지정하는 거보다 같은 방식으로 계산해주면 더 좋을 것 같습니다. 

이것에 대해서 lineHeight = fontsize * 1.5 해주고, topBottomPadding = 24.0 을 주는것만으로 47.0 이라는 
높이가 아닌 51.xxxxx 이란 값이 나오더라구요 

물론 값을 빼줌으로써 같은방식으로 height를 결정해줄 수도 있지만
이 값을 제거하는 상수를 정의해주는 행위와 빼는 행위 자체도 조금 번거로워보여서

내부컨텐츠(한글,영문)에 따른 변화가 없는 defaultHeight 47.0 으로 구현해뒀습니다!

2023-09-19 01:59 UTC, dev-summer approved these changes
고생하셨습니다~!

2023-09-19 04:53 UTC, merged